version: '3'

services:
  db:
    image: postgres
    volumes:
      - wiki_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_USER=joanne
      - POSTGRES_PASSWORD=1234
    
  web:
    build: .
    volumes:
      - wiki_database:/usr/src/app/entries
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  wiki_volume:
  wiki_database: